Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/LeadingCommentSpace:
  Exclude:
    - 'config.ru'

AllCops:
  TargetRubyVersion: 2.2
