require: rubocop-rspec
require: ditty/rubocop

Metrics/LineLength:
  Max: 120
Style/Documentation:
  Enabled: false
Layout/LeadingCommentSpace:
  Exclude:
    - 'config.ru'
AllCops:
  TargetRubyVersion: 2.6
