require: rubocop-rspec

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Layout/LeadingCommentSpace:
  Exclude:
    - 'config.ru'

AllCops:
  TargetRubyVersion: 2.2
