sudo: false
language: ruby
rvm:
  - 2.4.0
  - 2.3.3
  - 2.2.6
gemfile: Gemfile.ci
env:
  - DATABASE_URL="sqlite::memory:" ELASTICSEARCH_URL="http://localhost:9200" RACK_ENV=test
services:
  - elasticsearch
before_script:
  - sleep 10
before_install: gem install bundler -v 1.12.5
addons:
  code_climate:
    repo_token: 1f562305f75e169f5f5eca3b738fee879550c98e50099c2b9cd6ae71478007a0
after_success:
  - bundle exec codeclimate-test-reporter
